[package]
name = "cscall"
version = "0.1.0"
edition = "2024"

[dependencies]
dashmap = "6.1.0"
rand = "0.9.2"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
tracing = "0.1.44"
